USE [master]
GO
/****** Object:  Database [WebBanHoa]    Script Date: 19/11/2022 9:05:53 CH ******/
CREATE DATABASE [WebBanHoa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebBanHoa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WebBanHoa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebBanHoa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WebBanHoa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [WebBanHoa] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebBanHoa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WebBanHoa] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WebBanHoa] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WebBanHoa] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WebBanHoa] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WebBanHoa] SET ARITHABORT OFF 
GO
ALTER DATABASE [WebBanHoa] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [WebBanHoa] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WebBanHoa] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WebBanHoa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WebBanHoa] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WebBanHoa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WebBanHoa] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WebBanHoa] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WebBanHoa] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WebBanHoa] SET  ENABLE_BROKER 
GO
ALTER DATABASE [WebBanHoa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WebBanHoa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WebBanHoa] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WebBanHoa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WebBanHoa] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WebBanHoa] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WebBanHoa] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WebBanHoa] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WebBanHoa] SET  MULTI_USER 
GO
ALTER DATABASE [WebBanHoa] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WebBanHoa] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WebBanHoa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WebBanHoa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WebBanHoa] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WebBanHoa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [WebBanHoa] SET QUERY_STORE = OFF
GO
USE [WebBanHoa]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[MaAdmin] [int] IDENTITY(1,1) NOT NULL,
	[HoTenAdmin] [nvarchar](50) NULL,
	[DiaChiAdmin] [nvarchar](200) NULL,
	[DienThoaiAdmin] [char](10) NULL,
	[TenDNAdmin] [varchar](15) NULL,
	[MatKhauAdmin] [varchar](15) NULL,
	[NgaySinhAdmin] [datetime] NULL,
	[GioiTinhAdmin] [bit] NULL,
	[EmailAdmin] [varchar](50) NULL,
	[QuyenAdmin] [int] NULL,
 CONSTRAINT [PK_Admin] PRIMARY KEY CLUSTERED 
(
	[MaAdmin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTDONDATHANG]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTDONDATHANG](
	[MaHD] [int] NOT NULL,
	[MaSP] [int] NOT NULL,
	[SoLuong] [int] NULL,
	[DonGia] [decimal](9, 2) NULL,
	[ThanhTien]  AS ([SoLuong]*[DonGia]),
 CONSTRAINT [PK_CTDatHang] PRIMARY KEY CLUSTERED 
(
	[MaHD] ASC,
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTKHUYENMAI]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTKHUYENMAI](
	[MaKM] [int] NOT NULL,
	[MaSP] [int] NOT NULL,
 CONSTRAINT [PK_CTKHUYENMAI] PRIMARY KEY CLUSTERED 
(
	[MaKM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DONDATHANG]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONDATHANG](
	[MaHD] [int] IDENTITY(1,1) NOT NULL,
	[MaKH] [int] NULL,
	[NgayDH] [smalldatetime] NULL,
	[TriGia] [money] NULL,
	[DaGiao] [bit] NULL,
	[NgayGiaoHang] [smalldatetime] NULL,
	[TenNguoiNhan] [varchar](50) NULL,
	[DiaChiNhan] [nvarchar](50) NULL,
	[DienThoaiNhan] [varchar](15) NULL,
	[HTThanhToan] [bit] NULL,
	[HTGiaoHang] [bit] NULL,
 CONSTRAINT [PK_DonDatHang] PRIMARY KEY CLUSTERED 
(
	[MaHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKH] [int] IDENTITY(1,1) NOT NULL,
	[HoTenKH] [nvarchar](50) NULL,
	[DiaChiKH] [nvarchar](50) NULL,
	[DienThoaiKH] [varchar](10) NULL,
	[TenDN] [varchar](15) NULL,
	[MatKhau] [varchar](15) NULL,
	[NgaySinh] [smalldatetime] NULL,
	[GioiTinh] [bit] NULL,
	[Email] [varchar](50) NULL,
	[DaDuyet] [bit] NULL,
	[HinhAnh] [char](50) NULL,
 CONSTRAINT [PK_KhachHang] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHUYENMAI]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHUYENMAI](
	[MaKM] [int] NOT NULL,
	[TenKM] [nvarchar](50) NULL,
	[ChiTiet] [ntext] NULL,
	[NgayBD] [smalldatetime] NULL,
	[NgayKT] [smalldatetime] NULL,
	[PhanTramGiam] [int] NULL,
 CONSTRAINT [PK_KHUYENMAI] PRIMARY KEY CLUSTERED 
(
	[MaKM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHACUNGCAP]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHACUNGCAP](
	[MaNCC] [int] IDENTITY(1,1) NOT NULL,
	[TenNCC] [nvarchar](100) NOT NULL,
	[DiaChi] [nvarchar](150) NULL,
	[DienThoai] [char](10) NULL,
 CONSTRAINT [PK_NhaXuatBan] PRIMARY KEY CLUSTERED 
(
	[MaNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHANLOAI]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHANLOAI](
	[MaPL] [int] IDENTITY(1,1) NOT NULL,
	[TenPL] [nvarchar](50) NOT NULL,
	[ChiTiet] [ntext] NULL,
	[ChatLieu] [nvarchar](50) NULL,
 CONSTRAINT [PK_ChuDe] PRIMARY KEY CLUSTERED 
(
	[MaPL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rating]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rating](
	[RatingID] [int] NOT NULL,
	[MaKH] [int] NOT NULL,
	[MaSP] [int] NOT NULL,
	[NgayTao] [smalldatetime] NULL,
	[NgaySua] [smalldatetime] NULL,
	[Rank] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Rating] PRIMARY KEY CLUSTERED 
(
	[RatingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANPHAM]    Script Date: 19/11/2022 9:05:53 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[MaSP] [int] IDENTITY(1,1) NOT NULL,
	[TenSP] [nvarchar](200) NOT NULL,
	[DonViTinh] [nvarchar](50) NULL,
	[DonGia] [money] NULL,
	[MoTa] [ntext] NULL,
	[HinhMinhHoa] [varchar](50) NULL,
	[MaPL] [int] NULL,
	[MaNCC] [int] NULL,
	[NgayCapNhat] [smalldatetime] NULL,
	[SoLuongBan] [int] NULL,
	[SoLanXem] [int] NULL,
 CONSTRAINT [PK_Giay] PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADMIN] ADD  CONSTRAINT [DF__admin__GioiTinhA__3B75D760]  DEFAULT ((1)) FOR [GioiTinhAdmin]
GO
ALTER TABLE [dbo].[ADMIN] ADD  CONSTRAINT [DF__admin__QuyenAdmi__3C69FB99]  DEFAULT ((1)) FOR [QuyenAdmin]
GO
ALTER TABLE [dbo].[DONDATHANG] ADD  DEFAULT ((0)) FOR [DaGiao]
GO
ALTER TABLE [dbo].[DONDATHANG] ADD  DEFAULT ((0)) FOR [HTThanhToan]
GO
ALTER TABLE [dbo].[DONDATHANG] ADD  DEFAULT ((0)) FOR [HTGiaoHang]
GO
ALTER TABLE [dbo].[KHACHHANG] ADD  DEFAULT ((1)) FOR [GioiTinh]
GO
ALTER TABLE [dbo].[KHACHHANG] ADD  DEFAULT ((0)) FOR [DaDuyet]
GO
ALTER TABLE [dbo].[SANPHAM] ADD  CONSTRAINT [DF__giay__DonViTinh__412EB0B6]  DEFAULT ('cu?n') FOR [DonViTinh]
GO
ALTER TABLE [dbo].[SANPHAM] ADD  CONSTRAINT [DF__giay__SoLanXem__4222D4EF]  DEFAULT ((0)) FOR [SoLanXem]
GO
ALTER TABLE [dbo].[CTDONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_ctdathang_dondathang] FOREIGN KEY([MaHD])
REFERENCES [dbo].[DONDATHANG] ([MaHD])
GO
ALTER TABLE [dbo].[CTDONDATHANG] CHECK CONSTRAINT [FK_ctdathang_dondathang]
GO
ALTER TABLE [dbo].[CTDONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_ctdathang_Giay] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[CTDONDATHANG] CHECK CONSTRAINT [FK_ctdathang_Giay]
GO
ALTER TABLE [dbo].[CTKHUYENMAI]  WITH CHECK ADD  CONSTRAINT [FK_CTKHUYENMAI_KHUYENMAI] FOREIGN KEY([MaKM])
REFERENCES [dbo].[KHUYENMAI] ([MaKM])
GO
ALTER TABLE [dbo].[CTKHUYENMAI] CHECK CONSTRAINT [FK_CTKHUYENMAI_KHUYENMAI]
GO
ALTER TABLE [dbo].[CTKHUYENMAI]  WITH CHECK ADD  CONSTRAINT [FK_CTKHUYENMAI_SANPHAM] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[CTKHUYENMAI] CHECK CONSTRAINT [FK_CTKHUYENMAI_SANPHAM]
GO
ALTER TABLE [dbo].[DONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_DONDATHANG_KHACHHANG] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KHACHHANG] ([MaKH])
GO
ALTER TABLE [dbo].[DONDATHANG] CHECK CONSTRAINT [FK_DONDATHANG_KHACHHANG]
GO
ALTER TABLE [dbo].[Rating]  WITH CHECK ADD  CONSTRAINT [FK_Rating_KHACHHANG] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KHACHHANG] ([MaKH])
GO
ALTER TABLE [dbo].[Rating] CHECK CONSTRAINT [FK_Rating_KHACHHANG]
GO
ALTER TABLE [dbo].[Rating]  WITH CHECK ADD  CONSTRAINT [FK_Rating_SANPHAM] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[Rating] CHECK CONSTRAINT [FK_Rating_SANPHAM]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_giay_ChuDe] FOREIGN KEY([MaPL])
REFERENCES [dbo].[PHANLOAI] ([MaPL])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_giay_ChuDe]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_giay_NhaXuatBan] FOREIGN KEY([MaNCC])
REFERENCES [dbo].[NHACUNGCAP] ([MaNCC])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_giay_NhaXuatBan]
GO
ALTER TABLE [dbo].[CTDONDATHANG]  WITH CHECK ADD CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[CTDONDATHANG]  WITH CHECK ADD CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[DONDATHANG]  WITH CHECK ADD CHECK  (([TriGia]>(0)))
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [CK__giay__DonGia__5070F446] CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [CK__giay__DonGia__5070F446]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [CK__giay__SoLuongBan__5165187F] CHECK  (([SoLuongBan]>(0)))
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [CK__giay__SoLuongBan__5165187F]
GO
USE [master]
GO
ALTER DATABASE [WebBanHoa] SET  READ_WRITE 
GO
